name: fetch-data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'
    - cron: '30 14 * * *'
    - cron: '0 18 * * *'

jobs:
  fetch-data:
      runs-on: ubuntu-22.04
      timeout-minutes: 10
      steps:
      - name: Check out repository
        uses: actions/checkout@v3
  
      - name: Setup
        uses: ./.github/actions/setup
        with:
          python-version: 3.11.4
          poetry-version: 1.5.1
  
      - name: Fetch data
        working-directory: kos-loader
        shell: bash
        env:
          KOS_USERNAME: ${{ secrets.KOS_USERNAME }}
          KOS_PASSWORD: ${{ secrets.KOS_PASSWORD }}
          LOGLEVEL: info
        run: poetry run python3 -m kos_loader.kos_loader build/data.json

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: timetable-data
          path: kos-loader/build/data.json
          retention-days: 3

      - name: Push git subdirectory as branch
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: data
          FOLDER: kos-loader/build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_EMPTY_COMMITS: true
          COMMIT_NAME: 'GitHub Action by antoninkriz'
          COMMIT_EMAIL: 'github@users.noreply.github.com'
